### PR TITLE
Provide keyword to allow deletion of last failed backup

### LINKED ISSUE #310: Removing failed backups should be easier
Hi,

I tried to remove the last backup because it had failed and nagios kept nagging. I tried this:

`barman delete exampleserver latest`

That doesn't do what I meant to do. It deletes the latest successful backup.

### Solution:

Allow:

`barman delete exampleserver failed`

```patch
diff --git a/barman/cli.py b/barman/cli.py
index 32d3cc0..3e50df8 100644
--- a/barman/cli.py
+++ b/barman/cli.py
@@ -149,7 +149,7 @@ def backup_completer(prefix, parsed_args, **kwargs):
     for backup_id in sorted(backups, reverse=True):
         if backup_id.startswith(prefix):
             yield backup_id
-    for special_id in ('latest', 'last', 'oldest', 'first'):
+    for special_id in ('latest', 'last', 'oldest', 'first', 'failed'):
         if len(backups) > 0 and special_id.startswith(prefix):
             yield special_id
 
@@ -1286,6 +1286,8 @@ def parse_backup_id(server, args):
         backup_id = server.get_last_backup_id()
     elif args.backup_id in ('oldest', 'first'):
         backup_id = server.get_first_backup_id()
+    elif args.backup_id in ('failed',):
+        backup_id = server.get_last_backup_id(status_filter=(BackupInfo.FAILED,))
     else:
         backup_id = args.backup_id
     backup_info = server.get_backup(backup_id)

```

### PR DESCRIPTION
**Pull request by richyen**
Closes #310

### CODE REVIEW

**Comment by richyen** [comment]
My test results:
```
[root@barman docker]# barman list-backup barmantest                                                             
barmantest 20210930T064402 - Thu Sep 30 06:44:06 2021 - Size: 172.3 MiB - WAL Size: 0 B - WAITING_FOR_WALS      
barmantest 20210930T064359 - FAILED                                                                             
barmantest 20210930T064353 - Thu Sep 30 06:43:58 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T064347 - Thu Sep 30 06:43:51 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T064345 - FAILED                                                                             
barmantest 20210930T064342 - FAILED                                                                             
barmantest 20210930T062954 - Thu Sep 30 06:29:59 2021 - Size: 204.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062946 - Thu Sep 30 06:29:50 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062939 - Thu Sep 30 06:29:44 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062932 - Thu Sep 30 06:29:37 2021 - Size: 204.3 MiB - WAL Size: 32.0 MiB                    
barmantest 20210930T061137 - Thu Sep 30 06:14:08 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210929T224333 - Wed Sep 29 22:46:04 2021 - Size: 188.3 MiB - WAL Size: 144.0 MiB                   
[root@barman docker]# barman delete barmantest failed                                                           
Deleting backup 20210930T064359 for server barmantest
Deleted backup 20210930T064359 (start time: Thu Sep 30 07:06:24 2021, elapsed time: less than one second)
[root@barman docker]# barman list-backup barmantest                                                             
barmantest 20210930T064402 - Thu Sep 30 06:44:06 2021 - Size: 172.3 MiB - WAL Size: 0 B - WAITING_FOR_WALS      
barmantest 20210930T064353 - Thu Sep 30 06:43:58 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T064347 - Thu Sep 30 06:43:51 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T064345 - FAILED                                                                             
barmantest 20210930T064342 - FAILED                                                                             
barmantest 20210930T062954 - Thu Sep 30 06:29:59 2021 - Size: 204.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062946 - Thu Sep 30 06:29:50 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062939 - Thu Sep 30 06:29:44 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062932 - Thu Sep 30 06:29:37 2021 - Size: 204.3 MiB - WAL Size: 32.0 MiB                    
barmantest 20210930T061137 - Thu Sep 30 06:14:08 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210929T224333 - Wed Sep 29 22:46:04 2021 - Size: 188.3 MiB - WAL Size: 144.0 MiB                   
[root@barman docker]# barman delete barmantest failed                                                           
Deleting backup 20210930T064345 for server barmantest                                                           
Deleted backup 20210930T064345 (start time: Thu Sep 30 07:06:58 2021, elapsed time: less than one second)       
[root@barman docker]# barman delete barmantest failed                                                           
Deleting backup 20210930T064342 for server barmantest                                                           
Deleted backup 20210930T064342 (start time: Thu Sep 30 07:07:04 2021, elapsed time: less than one second)       
[root@barman docker]# barman list-backup barmantest                                                             
barmantest 20210930T064402 - Thu Sep 30 06:44:06 2021 - Size: 172.3 MiB - WAL Size: 0 B - WAITING_FOR_WALS      
barmantest 20210930T064353 - Thu Sep 30 06:43:58 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T064347 - Thu Sep 30 06:43:51 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062954 - Thu Sep 30 06:29:59 2021 - Size: 204.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062946 - Thu Sep 30 06:29:50 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062939 - Thu Sep 30 06:29:44 2021 - Size: 188.3 MiB - WAL Size: 32.0 MiB - WAITING_FOR_WALS 
barmantest 20210930T062932 - Thu Sep 30 06:29:37 2021 - Size: 204.3 MiB - WAL Size: 32.0 MiB                    
barmantest 20210930T061137 - Thu Sep 30 06:14:08 2021 - Size: 188.3 MiB - WAL Size: 48.0 MiB - WAITING_FOR_WALS 
barmantest 20210929T224333 - Wed Sep 29 22:46:04 2021 - Size: 188.3 MiB - WAL Size: 144.0 MiB
```

**Comment by mikewallace1979** [comment]
Thanks @richyen - the patch looks good.

Could you also update the following two bits of documentation with the new backup shortcut?
* https://github.com/EnterpriseDB/barman/blob/master/doc/barman.1.d/70-backup-id-shortcuts.md
* https://github.com/EnterpriseDB/barman/blob/master/doc/manual/43-backup-commands.en.md#backup-id-shortcuts

If you add those in a separate commit I'll squash and merge.

**Comment by richyen** [comment]
> Thanks @richyen - the patch looks good.
> 
> Could you also update the following two bits of documentation with the new backup shortcut?
> 
> * https://github.com/EnterpriseDB/barman/blob/master/doc/barman.1.d/70-backup-id-shortcuts.md
> * https://github.com/EnterpriseDB/barman/blob/master/doc/manual/43-backup-commands.en.md#backup-id-shortcuts
> 
> If you add those in a separate commit I'll squash and merge.

Hi @mikewallace1979 -- Thanks for the feedback.  I've updated the docs 👍

**Comment by mikewallace1979** [comment]
Thanks @richyen 🙌

**Pull request merged**
