### PR TITLE
#292 Introduce custom_compression magic

### PR DESCRIPTION
**Pull request by Thoro**
see #292

### CODE REVIEW

**Comment by mikewallace1979** [comment]
Hi @Thoro - thanks for taking the time to make this PR and update the tests.

I rebased your branch onto the current master [here](https://github.com/EnterpriseDB/barman/tree/dev/Thoro-magic_custom_compression) with a view to resolving the issue with the `identify_compression` method, however while I was there I noticed that `barman wal-archive` and `barman get-wal` are already able to handle custom compression albeit through a simpler method than the one you are proposing. Specifically, if a custom compression algorithm is in the configuration then it is used in the case that no recognised compression magic is found.

In the case of wal-archive, the compression is actually determined after the call to [WalFileInfo.from_file](https://github.com/EnterpriseDB/barman/pull/294/files#diff-65121e20a7f921ae67836deb2ebccaae8ae35211b28b1284730bf65c96e5e08fL507) when we call [CompressionManager.get_default_compressor](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/wal_archiver.py#L141) which will return the configured compression.

In the code path for get-wal, the CompressionManager [get_wal_file_info](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/server.py#L1858) function is called which will result in the custom compressor being used [if the compression cannot be identified](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/infofile.py#L348-L351).

So although allowing the custom compression magic to be specified is a worthy goal it is not necessary for the existing barman functions that support compression (though as you note in #291 there are other functions which do not currently allow compression to be specified).

That being the case I don't think we want to merge this work in its current form. If we could come up with an implementation which avoided having multiple `identify_compression` methods or multiple `from_file*` methods then we could reconsider however I suspect that requires more rework of the existing barman code.

**Comment by Thoro** [comment]
@mikewallace1979 

> I rebased your branch onto the current master [here](https://github.com/EnterpriseDB/barman/tree/dev/Thoro-magic_custom_compression) with a view to resolving the issue with the `identify_compression` method, however while I was there I noticed that `barman wal-archive` and `barman get-wal` are already able to handle custom compression albeit through a simpler method than the one you are proposing. Specifically, if a custom compression algorithm is in the configuration then it is used in the case that no recognised compression magic is found.

This is correct, but does not allow the actual use-case I was proposing, the proposed use case was to pre-compress the wal files, so that barman is not compressing them a second time. (although I barely remember doing that PR) Since barman does not recognize the custom magic, it will just happily compress the files a **second** time.

**Comment by mikewallace1979** [comment]
@Thoro thanks for clarifying - I see it now, down on [L349](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/wal_archiver.py#L349-L350). Currently `wal_info.compression` is going to have `None`, even if the file has already been compressed with the custom compression algorithm. With this patch the custom compression will have been detected and therefore that second compression will be avoided.

**Comment by mikewallace1979** [comment]
Merged in #415 - thanks for the contribution @Thoro

**Comment by Thoro** [comment]
Wow thanks, didn‘t expect that to still happen 👍

have to upgrade to master now 😁

**Comment by mikewallace1979** [comment]
No worries and thanks again - this is going out in the 2.16 release which, if things go to plan, should be out by the end of the week.

**Pull request closed without merging**
