### PR TITLE
✨ feat: cluster awareness added

### PR DESCRIPTION
**Pull request by mhkarimi1383**
On clustered PostgreSQL instances when master changes we have to run

```bash
barman receive-wal --create-slot
barman receive-wal --reset
```

So I added a new check in `cron` command and if slot is not active run the above commands (or functions) automatically

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
@mikewallace1979 
Hi, can you review this?
we are having a bad experience with our clusters using barman

**Comment by mikewallace1979** [comment]
Hi @mhkarimi1383 - it looks like you should be able to achieve part of what this patch does by setting [`create_slot = auto`](https://docs.pgbarman.org/release/3.5.0/#how-to-configure-the-wal-streaming) in the Barman config.

The automatic usage of the reset option is going to be problematic in some scenarios since it causes the removal of any existing `.partial` files - while that may be the right action in the particular case you are considering, there are going to be other times where streaming should still resume from an existing `.partial` file.

There are definitely improvements we need to make for Barman so that it can work better in clustered environments and we are planning on doing some work on this later in the year.

Can you share any more details of the specific problem you are trying to solve with this PR?

**Comment by mhkarimi1383** [comment]
when our clusters (using https://github.com/basalam/kaastolon) fail-over the master node we should run both commands to make backup working, and WAL files are not found from the server and we have to do `reset-wal`

**Comment by martinmarques** [comment]
Are you using some failover VIP or updating DNS records to make barman failover to the current primary node?

**Comment by mhkarimi1383** [comment]
> Are you using some failover VIP or updating DNS records to make barman failover to the current primary node?

We are using connecting Barman to kaastolon Proxy, it will proxy connections to master nodes, when failover happens connections will drop, and upstream node changes

**Comment by martinmarques** [comment]
We will not be moving forward with this PR. I would suggest looking at the models feature we added to the last release which we are using for integration with Patroni

**Comment by mhkarimi1383** [comment]
> We will not be moving forward with this PR. I would suggest looking at the models feature we added to the last release which we are using for integration with Patroni

What about CloudNativePG (It should work) or Stolon (also Kaastolon)

**Pull request closed without merging**
